### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by cesss** [adolfopa/cstow#3]
Hi!

Thanks a lot for developing cstow. I'm trying to use it on Mac OS X. However, when running the tests, I get this output, which ends in error. Do you consider cstow production-ready, or should I expect it to be in beta status? (note: I replaced ` by ' in the output, because of the Markdown syntax meanings)

```
mac:cstow-master cesss$ make test
cd src && make test
--- tush-expanded.nCgq3	2017-01-23 21:23:29.000000000 +0100
+++ -	2017-01-23 21:23:29.000000000 +0100
@@ -181,8 +181,7 @@
 '''sh
 $ cstow -d packages pkg
 $ cstow -d packages -n pkg
-@ cstow: CONFLICT: /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/f0 vs ../packages/pkg/d0/f0
-@ 
+@ cstow: CONFLICT: /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/d1/f1 vs ../../packages/pkg/d0/d1/f1\n
 ? 1
 $ rm -rf d0
 '''
@@ -195,17 +194,17 @@
 '''sh
 $ cstow -d packages -v pkg
 | mkdir /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0
-| ln -s /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/packages/pkg/d0/f0 /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/f0
 | mkdir /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/d1
 | ln -s /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/packages/pkg/d0/d1/f1 /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/d1/f1
+| ln -s /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/packages/pkg/d0/f0 /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/f0
 '''
 
 It works both when stowing and unstowing:
 
 '''sh
 $ cstow -d packages -v -D pkg
-| rm /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/f0
 | rm /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/d1/f1
 | rmdir /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/d1
+| rm /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0/f0
 | rmdir /Users/cesss/cstow/cstow-master/src/tush-scratch.EjpDj/d0
 '''
make[1]: *** [test] Error 1
make: *** [test] Error 2
mac:cstow-master cesss$ 

```

**Comment by cesss** [comment]
I tried both the master branch and the C11 branch, and `make test` fails exactly in the same way in both branches.

Is it possible to find what's the error exactly? I'm not seeing any error message in the log, as you can see (only the "CONFLICT" messages, which I guess are expected warnings, as the tests seem to continue after that point).

**Comment by adolfopa** [comment]
Hey @cesss 

The tests are failing in OS X due to the order in which directory contents are returned by the  `readdir_r` function (the tests assume Linux/EXT2 ordering, as Travis runs them under Ubuntu). That order is filesystem dependent, so there's not much to do here. Anyway, cstow does not depend on a particular ordering, so this is really not a problem.

About its stability, I've been using this for more than 5 years now, so I would say it is pretty stable.

Thanks!

**Comment by cesss** [comment]
Yes, it does look very rock-solid. I've been using it with no problems these weeks (apart from those failed tests, that can be ignored). Thanks a lot for developing it!

**Comment by adolfopa** [comment]
Thanks to you for using it :-)
